#include <CL/sycl.hpp>
#include <algorithm>
#include <cstddef>
#include <hipSYCL/sycl/access.hpp>
#include <hipSYCL/sycl/buffer.hpp>
#include <hipSYCL/sycl/context.hpp>
#include <hipSYCL/sycl/device.hpp>
#include <hipSYCL/sycl/libkernel/accessor.hpp>
#include <hipSYCL/sycl/libkernel/id.hpp>
#include <hipSYCL/sycl/libkernel/stream.hpp>
#include <iostream>
#include <ostream>
#include <string>
#include <vector>